setlocal formatoptions+=r
setlocal formatoptions+=o
setlocal formatoptions-=c
setlocal comments=b:-\ [\ ]
setlocal comments+=b:*\ [\ ]
setlocal comments+=b:*,b:+,b:-
setlocal comments+=b:>
setlocal formatoptions+=o
setlocal foldexpr=MarkdownFold()
setlocal foldmethod=expr
