addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip
      - python3-setuptools

before_install:
  - pip3 install --user vim-vint

script:
  - cd vim && vint .vimrc .vim/pack/local .vim/after .vim/autoload .vim/colors .vim/compiler .vim/indent .vim/syntax .vim/plugin .vim/ftplugin
