#!/bin/sh
alias ls='ls --color=auto'
alias df='df -h'
alias du='du -h -c'
alias back='cd $OLDPWD'
alias ..="cd ..; ls"
alias ...="cd ../..; ls"
alias ....="cd ../../..; ls"
alias .....="cd ../../../..; ls"
alias ......="cd ../../../../..; ls"
alias lt='ls -lrt'
unalias l
alias l='ls -lFh'

alias mv='mv -i'
alias cp='cp -i'
alias j=jobs

alias python='python3'
alias search='find . -type f -name'
alias vi='custom_vim'

if [[ $(uname -s) == CYGWIN* ]]; then
    alias home='cd /c/Users/jzinkduda'
    alias documents='cd /c/Users/jzinkduda/Documents'
    alias desktop='cd /c/Users/jzinkduda/Desktop'
    alias downloads='cd /c/Users/jzinkduda/Downloads'
    alias repo='cd /c/GITRepo'
    alias apps='cd /c/apps'
    alias promote='cd /i/Public/WSO2_ESBSetup/promote'

    alias wls='cd /c/apps/wls12120/user_projects/domains/mydomain/servers/myserver/logs'
    alias wso='cd /c/apps/wso2esb-5.0.0/bin'

    alias mcar='cp "`ls -dtr1 *_Deployment/target/* | tail -1`" /h/car-files/'
    alias esb='sh /c/apps/wso2esb-5.0.0/bin/wso2server.sh'
    alias esblog='less +F /c/apps/wso2esb-5.0.0/repository/logs/wso2carbon.log'
    alias subl='/c/Program\ Files/Sublime\ Text\ 3/subl.exe'
    alias build='mvnc clean install; mcar'
fi

