#!/bin/sh
alias ls='ls --color=auto'
alias ..="cd ..; ls"
alias ...="cd ../..; ls"
alias ....="cd ../../..; ls"
alias .....="cd ../../../..; ls"
alias ......="cd ../../../../..; ls"
alias lt='ls -lrt'
alias l='ls -lFh'
alias la='ls -lAh'

alias mv='mv -i'
alias cp='cp -i'
alias j=jobs
alias vi=vim

alias python='python3'
alias pip='pip3'
alias search='find . -type f -name'
alias vimup='vim +helptags\ ALL +PlugUpgrade +PlugUpdate'

alias mcar='cp "`/bin/ls -dtr1 *_Deployment/target/* | tail -1`" /h/car-files/'
alias build='mvn install; mcar'

alias cvi='vi -u ~/dotfiles/microvimrc --noplugin -N'
alias e='vi -Nu ~/dotfiles/microvimrc'
alias mvi='vi -u ~/dotfiles/minvimrc -N'
alias nvi='vi -u ~/dotfiles/nanovimrc -N'

alias grep='grep --color=auto --exclude-dir=.git'
alias rg='rg -g ''!tags'''
alias history='fc -il 1'
alias md='mkdir -p'

if [[ $(uname -s) == CYGWIN* ]]; then
    alias home='cd /cygdrive/c/Users/jzinkduda'
    alias documents='cd /cygdrive/c/Users/jzinkduda/Documents'
    alias desktop='cd /cygdrive/c/Users/jzinkduda/Desktop'
    alias downloads='cd /cygdrive/c/Users/jzinkduda/Downloads'
    alias repo='cd /cygdrive/c/GITRepo'
    alias apps='cd /cygdrive/c/apps'
    alias promote='cd /cygdrive/i/Public/WSO2_ESBSetup/promote'

    alias wls='cd /cygdrive/c/apps/wls12120/user_projects/domains/mydomain/servers/myserver/logs'
    alias wso='cd /cygdrive/c/apps/wso2esb-5.0.0/bin'

    alias esb='sh /cygdrive/c/apps/wso2esb-5.0.0/bin/wso2server.sh'
    alias esblog='less +F /cygdrive/c/apps/wso2esb-5.0.0/repository/logs/wso2carbon.log'
    alias subl='/cygdrive/c/Program\ Files/Sublime\ Text\ 3/subl.exe'
fi
