#!/bin/sh

function git_update() {
    if ! git diff-index --quiet HEAD --; then
        return true
    else
        return false
    fi
}

function check_repos() {
    for d in ./*/
    do
        cd "$d"
        echo "$d"
        git update-index -q --refresh
        if [[ -n `git status --porcelain` || -n $(git rev-list --left-right HEAD...@'{u}' 2>/dev/null) ]]; then
            git status -u
        fi
        cd ..
    done
}

function custom_vim() {
    local jobsresult=$(jobs)
    local jobsdir=$(jobs -d)
    local vimresult=$(echo $jobsdir | grep -n vim)
    if [[ -n $vimresult ]]; then
        if [[ $(jobs -d | grep -B $vimresult[1,1] -oPm1 '(?<=\(pwd : ).*(?=\))') = $PWD ]]; then
            local jobnum=$(echo $jobsresult | grep -n vim)
            eval "fg %$jobnum[1,1]"
        else
            eval "vim $@"
        fi
    else
        eval "vim $@"
    fi
    return true
}
