#!/bin/sh

function git_update() {
    if ! git diff-index --quiet HEAD --; then
        return true
    else
        return false
    fi
}

function check_repos() {
    for d in ./*/
    do
        cd "$d"
        echo "$d"
        git update-index -q --refresh
        if [[ -n `git status --porcelain` || -n $(git rev-list --left-right HEAD...@'{u}' 2>/dev/null) ]]; then
            git status -u
        fi
        cd ..
    done
}

function custom_vim() {
    local jobsresult=$(jobs)
    local jobsdir=$(jobs -d)
    local vimresult=$(echo $jobsdir | grep -n vim)
    if [[ $@ == '' &&  -f $PWD/.git/Session.vim ]]; then
        flags=' -S .git/Session.vim'
    else
        flags=''
    fi
    if [[ -n $vimresult ]]; then
        if [[ $(jobs -d | grep -B $vimresult[1,1] -oPm1 '(?<=\(pwd : ).*(?=\))') = $PWD ]]; then
            local jobnum=$(echo $jobsresult | grep -n vim)
            eval "fg %$jobnum[1,1]"
        else
            eval "vim $flags $@"
        fi
    else
        eval "vim $flags $@"
    fi
    return true
}

function getssl() {
    openssl s_client -showcerts -connect $1 </dev/null 2>/dev/null|openssl x509 -outform PEM >$2
}

function buildp() {
    mvnc clean install -P$1; mcar
}

zstyle -s ":vcs_info:git:*:-all-" "command" _omz_git_git_cmd
: ${_omz_git_git_cmd:=git}

# The name of the current branch
# Back-compatibility wrapper for when this function was defined here in
# the plugin, before being pulled in to core lib/git.zsh as git_current_branch()
# to fix the core -> git plugin dependency.
function current_branch() {
  git_current_branch
}
# The list of remotes
function current_repository() {
  if ! $_omz_git_git_cmd rev-parse --is-inside-work-tree &> /dev/null; then
    return
  fi
  echo $($_omz_git_git_cmd remote -v | cut -d':' -f 2)
}
# Pretty log messages
function _git_log_prettily(){
  if ! [ -z $1 ]; then
    git log --pretty=$1
  fi
}
# Warn if the current branch is a WIP
function work_in_progress() {
  if $(git log -n 1 2>/dev/null | grep -q -c "\-\-wip\-\-"); then
    echo "WIP!!"
  fi
}

gdv() { git diff -w "$@" | view - }
compdef _git gdv=git-diff

function gfg() { git ls-files | grep $@ }
compdef _grep gfg

ggf() {
  [[ "$#" != 1 ]] && local b="$(git_current_branch)"
  git push --force origin "${b:=$1}"
}

ggfl() {
[[ "$#" != 1 ]] && local b="$(git_current_branch)"
git push --force-with-lease origin "${b:=$1}"
}
compdef _git ggf=git-checkout

ggl() {
  if [[ "$#" != 0 ]] && [[ "$#" != 1 ]]; then
    git pull origin "${*}"
  else
    [[ "$#" == 0 ]] && local b="$(git_current_branch)"
    git pull origin "${b:=$1}"
  fi
}
compdef _git ggl=git-checkout

ggp() {
  if [[ "$#" != 0 ]] && [[ "$#" != 1 ]]; then
    git push origin "${*}"
  else
    [[ "$#" == 0 ]] && local b="$(git_current_branch)"
    git push origin "${b:=$1}"
  fi
}
compdef _git ggp=git-checkout

ggpnp() {
  if [[ "$#" == 0 ]]; then
    ggl && ggp
  else
    ggl "${*}" && ggp "${*}"
  fi
}
compdef _git ggpnp=git-checkout

ggu() {
  [[ "$#" != 1 ]] && local b="$(git_current_branch)"
  git pull --rebase origin "${b:=$1}"
}
compdef _git ggu=git-checkout
