#! sh

export LS_COLORS='di=00;94:ex=00;92:tw=00;94:ow=00;94:ln=00;36:*.mp4=00;35:*.tar=00;31:*.deb=00;31:*.tgz=00;31:*.zip=00;31:*.rar=00;31:*.jar=00;31:*.car=00;31:*.war=00;31:*.gz=00;31:*.bz2=00;31:*.png=00;35:*.jpg=00;35:*.jpeg=00;35:*.bmp=00;35:*.gif=00;35:*.vim=00;33:*vimrc=00;33:*.py=00;95:*.xml=00;91:*.md=00;97'

export ANSIBLE_VAULT_PASSWORD_FILE=~/.vault_pass.txt

export EDITOR=vim\ --noplugin\ -Nu\ ~/dotfiles/nanovimrc
export VISUAL=vim\ --noplugin\ -Nu\ ~/dotfiles/nanovimrc

export RIPGREP_CONFIG_PATH=~/.ripgrep

export PATH=$PATH:/snap/bin/
export PATH="$HOME/.bin:$HOME/bin:$HOME/.local/bin:$PATH"

if type fd > /dev/null; then
    export FZF_DEFAULT_COMMAND='fd --type f'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND='fd --type d'
elif type rg > /dev/null; then
    export FZF_DEFAULT_COMMAND='rg --files'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
elif type ag > /dev/null; then
    export FZF_DEFAULT_COMMAND='ag -l'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi
