unbind C-b
set -g prefix C-a
setw -g mode-keys vi
bind-key a send-prefix

bind-key -n M-C-h previous-window
bind-key -n M-C-l next-window
bind-key s set status
bind-key * kill-session

setw -g monitor-activity on
set -g visual-activity on

set -g base-index 1
set -g pane-base-index 1

######################
### DESIGN CHANGES ###
######################
set-window-option -g automatic-rename on
set-option -g set-titles on
set -g renumber-windows on

# panes
set -g pane-border-fg colour238
set -g pane-active-border-fg colour238

## Status bar design
# status line
set -g status-justify centre
set -g status-bg default
set -g status-fg colour12
set -g status-interval 2

# messaging
set -g message-fg colour234
set -g message-bg yellow
set -g message-command-fg blue
set -g message-command-bg colour234

#window mode
set -g window-style 'bg=colour236'
set -g window-active-style 'bg=colour234'

# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

set -g default-terminal "xterm-256color"

# The modes {
setw -g clock-mode-colour colour135
setw -g mode-attr bold
setw -g mode-fg colour196
setw -g mode-bg colour238

# }
# The statusbar {
set-option -g status on
set-option -g status-interval 2

set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour254
set -g status-left '#[fg=colour68] #(echo $USER) #[fg=colour240]#h '
set -g status-right '#[fg=colour111,nobold] %b %d %a #[fg=colour68,nobold]%l:%M:%S %P '
set -g status-right-length 50
set -g status-left-length 50
set -g window-status-separator ''

setw -g window-status-current-fg colour235
setw -g window-status-current-bg colour236
setw -g window-status-current-attr bold
setw -g window-status-current-format '#[bg=colour167,fg=colour234] #I #[fg=colour167,bg=colour234] #W '

setw -g window-status-fg colour240
setw -g window-status-bg colour234
setw -g window-status-attr none
setw -g window-status-format '#[fg=colour243,bg=colour236] #I #[bg=colour234] #W '
setw -g window-status-separator ' '

setw -g window-status-bell-attr bold
setw -g window-status-bell-fg colour255
setw -g window-status-bell-bg colour1

# }
# The messages {

set -g message-attr bold
set -g message-fg colour232
set -g message-bg colour166

# }

# smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqP 'vi' && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqP 'vi' && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iqP 'vi' && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iqP 'vi' && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iqP 'vi' && tmux send-keys 'C-\\') || tmux select-pane -l"

# use emacs keybinds in status line
set -g status-keys emacs

set -sg escape-time 0

set-option -g mouse on
set -g mouse on

bind -n WheelUpPane	select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane	select-pane -t= \;				   send-keys -M
