unbind C-b
set -g prefix C-a
setw -g mode-keys vi
bind -r a send-prefix
bind -r C-a send-prefix

bind C-c new-window
bind -n M-C-h previous-window \; refresh-client
bind -n M-C-l next-window \; refresh-client
bind * kill-session
bind Z select-pane -l \; resize-pane -Z
bind % split-window -h -c '#{pane_current_path}'
bind '"' split-window -v -c '#{pane_current_path}'
run-shell "$TMUX_CUSTOM/version_check.sh"
bind ] run-shell "tmux set-buffer \"$(xclip -o)\"; tmux paste-buffer"
bind j run-shell -b "ssh -f -q jump keepalive"

# smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqP 'vi' && tmux send-keys C-h) || tmux select-pane -L \\; refresh-client"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqP 'vi' && tmux send-keys C-j) || tmux select-pane -D \\; refresh-client"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iqP 'vi' && tmux send-keys C-k) || tmux select-pane -U \\; refresh-client"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iqP 'vi' && tmux send-keys C-l) || tmux select-pane -R \\; refresh-client"
bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iqP 'vi' && tmux send-keys 'C-\\') || tmux select-pane -l"

setw -g main-pane-width 200

# use emacs keybinds in status line
set -g status-keys emacs

set -sg escape-time 0

set -g focus-events on

# mouse mode
set -g mouse on

bind -n WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane select-pane -t= \; send-keys -M

######################
### DESIGN CHANGES ###
######################
# Title and numbers {{{
set -g base-index 1
set -g pane-base-index 1
setw -g automatic-rename on
set -g set-titles on
set -g renumber-windows on
set -g history-limit 10000
# }}}

# panes {{{
set -g pane-border-fg colour235
set -g pane-border-bg colour235
set -g pane-active-border-fg colour235
set -g pane-active-border-bg colour235
# }}}

# messaging
set -g message-style fg=colour46,bold,bg=colour232

#window mode {{{
set -g window-style bg=default
set -g window-active-style bg=default
# }}}

# Bells {{{
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
# }}}

set -g default-terminal "xterm-256color"
set -g terminal-overrides ",xterm-256color:Tc"
# The modes {{{
setw -g clock-mode-colour colour135
setw -g clock-mode-style 12
setw -g mode-attr bold
setw -g mode-fg colour135
setw -g mode-bg colour237
# }}}

# The statusbar {{{

set -g status on

set -g status-position bottom
set -g status-justify left
set -g status-bg colour236
set -g status-fg colour245
set -g status-left ' #[fg=colour248]#S § '
set -g status-right '#{battery_status_fg}#{battery_percentage}#[fg=default]#{battery_remain}#[fg=colour68,nobold] %I:%M:%S %P#[bg=default,fg=colour179] #{username} #[fg=default]#{hostname} '
set -g status-right-length 90
set -g status-left-length 30
set -g status-interval 1

setw -g window-status-current-fg colour234
setw -g window-status-current-bg colour167

setw -g window-status-fg colour248
setw -g window-status-bg colour236

setw -g window-status-bell-attr bold
setw -g window-status-bell-fg colour255
setw -g window-status-bell-bg colour1

# }}}

set -g @resurrect-processes 'ssh sshrc bash'

run-shell "~/dotfiles/tmux/custom_tmux.sh"
run-shell "~/dotfiles/tmux/tmux-resurrect/resurrect.tmux"
