set nocompatible
filetype off
set runtimepath+=~/.vim/bundle/Vundle.vim
call vundle#rc()

Plugin 'VundleVim/Vundle.vim'
Plugin 'w0rp/ale'
Plugin 'kien/ctrlp.vim'
Plugin 'vim-scripts/c.vim'
Plugin 'raimondi/delimitmate'
Plugin 'junegunn/goyo.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'wting/gitsessions.vim'
Plugin 'luochen1990/rainbow'
Plugin 'gerw/vim-HiLinkTrace'
Plugin 'vim-airline/vim-airline'
Plugin 'easymotion/vim-easymotion'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'tmux-plugins/vim-tmux'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
"Plugin 'garbas/vim-snipmate'
Plugin 'Shougo/neosnippet'
Plugin 'Shougo/neosnippet-snippets'
Plugin 'justmao945/vim-clang'
Plugin 'shougo/neocomplete.vim'
"Plugin 'ervandew/supertab'
"Plugin 'valloric/youcompleteme'
Plugin 'christoomey/vim-tmux-navigator'

call vundle#end()
filetype plugin indent on


" Set 999 lines to the cursor - when moving vertically using j/k
" Keeps cursor centered
set so=999
set sidescroll=1
set sidescrolloff=15

runtime macros/matchit.vim

" Turn on the WiLd menu
set wildmenu

set wildmode=longest,list
" Ignore compiled files
set wildignore+=*.o,*~,*.pyc,*.versionsBackup
set wildignore+=*/target/*

" Don't insert comment when using 'o'
au FileType * set fo-=o
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
set sessionoptions-=options

"Always show current position
set ruler

" Height of the command bar
set cmdheight=1

" A buffer becomes hidden when it is abandoned
set hidden

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

set breakindent
set breakindentopt=shift:2

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch

" Don't redraw while executing macros (good performance config)
set lazyredraw

" For regular expressions turn magic on
set magic

" Show matching brackets when text indicator is over them
set showmatch
" How many tenths of a second to blink when matching brackets
set mat=2

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Use 256 colors
set t_Co=256

" Make splits behave better
set splitbelow
set splitright

" General options
let python_hightlight_all=1
set background=dark
syntax on
colorscheme hybrid_material
set nu
set relativenumber
set numberwidth=1
set hlsearch
set clipboard=unnamed
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set noshowmode
set nowrap
set laststatus=2
set cindent
set cinkeys-=0#
set indentkeys-=0#
let g:is_posix = 1
set term=xterm-256color
"set nofoldenable

" make leader a more sane keybinding
let mapleader = "\<Space>"

" remap localleader
let maplocalleader = ","

" Change tabs to be 2 spaces for xml files
autocmd FileType xml setlocal shiftwidth=2 tabstop=2 softtabstop=2 noexpandtab
" enable xml folding
let g:xml_syntax_folding=1

autocmd BufNewFile,BufRead *.zsh-theme set filetype=zsh
autocmd BufNewFile,BufRead *.dbs set filetype=xml

" fold based on syntax
set foldmethod=syntax

autocmd FileType python setlocal foldmethod=indent

" Make enter create a new line
nnoremap <CR> o<ESC>

let g:ycm_key_invoke_completion = "<Leader>i"

" make 0 work better
nnoremap 0 ^
nnoremap ^ 0

" Better backups
" set nobackup
set backupdir=/tmp
set noswapfile

" Make moving around splits easier
nnoremap <Leader>v :vs\|bn<CR>

" Fold toggle keybind
nnoremap <Leader>a za

" Make <Leader>q clear highlighting from searches
nnoremap <silent> <Leader>q :noh<return><esc>

" emacs bindings
" <c-a> don't work with tmux
" inoremap <c-a> <esc>I
inoremap <c-e> <esc>A
" nnoremap <c-a> <home>
nnoremap <c-e> <end>

"autocmd BufWritePost *.py :PymodeLintAuto
set foldlevel=99

" make it easier to use buffers
nnoremap <Leader>l :bn<CR>
nnoremap <Leader>h :bp<CR>
map <Leader><Leader> :b#<CR>
map <Leader>p :bp<CR>

" more standard 'close tab' behavior
nnoremap <C-x> :bn\|bd #<CR>

" treat wrapped lines as different lines
noremap j gj
noremap k gk
noremap gj j
noremap gk k

" easier to go to end/beginning of lines
noremap L $
noremap H ^

" Buffer keymappings
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>

map <Leader>o :only<CR>

" Close preview window when leaving insert mode
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" netrw setup {{{
let g:netrw_winsize = -28
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4


" }}}

" Easier to save
nnoremap <C-s> :w<CR>
nnoremap q :q<CR>
nnoremap Q q
imap <C-s> <Esc>:w<CR>i
"nnoremap <Leader>x :q<CR>

" Easier to exit insert mode
inoremap jk <Esc>

" keybinding to see whitespace
nnoremap <Leader>z :set invlist<CR>
set listchars=tab:>-,trail:~,extends:>,space:.,eol:$

"make folding work better with insert mode
autocmd InsertEnter * if !exists('w:last_fdm') | let w:last_fdm=&foldmethod | setlocal foldmethod=manual | endif
autocmd InsertLeave,WinLeave * if exists('w:last_fdm') | let &l:foldmethod=w:last_fdm | unlet w:last_fdm | endif

" neocomplete setup {{{
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#enable_auto_select = 1
"inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
            \ "\<Plug>(neosnippet_expand_or_jump)"
            \: pumvisible() ? "\<C-n>" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
            \ "\<Plug>(neosnippet_expand_or_jump)"
            \: "\<TAB>"
let g:neosnippet#enable_snipmate_compatibility = 1

if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
endif

" python setup
autocmd FileType python setlocal omnifunc=jedi#completions
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#smart_auto_mappings = 0
let g:neocomplete#force_omni_input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'


" clang setup
" disable auto completion for vim-clang
let g:clang_auto = 0
" default 'longest' can not work with neocomplete
let g:clang_c_completeopt = 'longest,menuone,preview'
let g:clang_cpp_completeopt = 'longest,menuone,preview'
"let g:clang_library_path='/usr/lib'
autocmd FileType c setlocal omnifunc=ClangComplete
let g:neocomplete#force_omni_input_patterns.c =
      \ '\h\%(\w\|\.\|->\)*'
let g:neocomplete#force_omni_input_patterns.cpp =
      \ '\h\w*\%(\.\|->\)\w*\|\h\w*::\w*'
let g:neocomplete#force_omni_input_patterns.objc =
      \ '\[\h\w*\s\h\?\|\h\w*\%(\.\|->\)'
let g:neocomplete#force_omni_input_patterns.objcpp =
      \ '\[\h\w*\s\h\?\|\h\w*\%(\.\|->\)\|\h\w*::\w*'
let g:clang_verbose_pmenu = 1
"let g:clang_complete_auto = 0
"let g:clang_auto_select = 0
"let g:clang_omnicppcomplete_compliance = 0
"let g:clang_make_default_keymappings = 0

" }}}

"" Supertab setup {{{
"let g:SuperTabDefaultCompletionType = "context"
"let g:SuperTabContextTextOmniPrecedence = ['&omnifunc', '&completefunc']
"" let g:SuperTabLongestHighlight = 1
"let g:SuperTabCrMapping = 1
"" }}}

" Ansible setup {{{
let g:ansible_unindent_after_newline = 1
let g:ansible_attribute_highlight = "a"
" let g:ansible_name_highlight = 'd'
let g:ansible_extra_keywords_highlight = 1

" ALE setup {{{
nmap <silent> ]e <Plug>(ale_next_wrap)
nmap <silent> [e <Plug>(ale_previous_wrap)
let g:ale_python_flake8_options = '--max-line-length 99'
let g:ale_virtualenv_dir_names = []
let g:ale_lint_on_text_changed = 'never'
" }}}

" Jedi setup {{{
let g:jedi#show_call_signatures = 2

" }}}

" SnipMate setup {{{
let g:snipMate = {}
let g:snipMate.snippet_version = 1
"imap <TAB> <Plug>snipMateTrigger
"imap <TAB> <Plug>snipMateNextOrTrigger

" }}}

" Easymotion setup {{{
map <Leader> <Plug>(easymotion-prefix)
nmap s <Plug>(easymotion-overwin-f)
map / <Plug>(easymotion-sn)
omap / <Plug><easymotion-tn)
let g:EasyMotion_startofline = 0

" }}}

" Airline setup {{{
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
let g:airline#extensions#tabline#buffer_min_count = 2
"set laststatus=2

"let g:airline_section_c = '%t'
let g:airline_section_x = ''
let g:airline_section_y = '%y %{&ff}'
let g:airline_section_z = '%3l:%2c'
"let g:airline_section_error = ''
"let g:airline_section_warning = ''

let g:airline#extensions#default#section_truncate_width = {
       \ 'b': 59,
       \ 'x': 79,
       \ 'y': 69,
       \ 'z': 39,
       \ 'warning': 69,
       \ 'error': 69,
       \ }
" }}}

" Set up ctrlP
set runtimepath^=~/.vim/bundle/ctrlp.vim

" Set up rainbow parens
let g:rainbow_active = 1

let g:rainbow_conf = {
            \ 'ctermfgs': [14, 11, 10, 9, 6, 5],
            \ 'separately': {
            \   'xml': 0,
            \   'vim': 0,
            \   'python': 0,
            \   'sh': 0,
            \   'c': 0
            \  }
            \}


if has("gui_running")
    set guifont=Liberation\ Mono\ for\ Powerline\ Regular\ 11
    set guioptions-=T
    set guioptions+=e
    set guioptions-=m
    set guitablabel=%M\ %t
else
    " Set line number color as darkgray
    highlight LineNr ctermfg=8
    highlight Cursor cterm=reverse
    let g:hybrid_custom_term_colors=1
endif

" More Airline {{{

"if has("win32unix")
"    let g:airline_symbols_ascii = 1
"else
    let g:airline_powerline_fonts = 1
"end

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_skip_empty_sections = 1
let g:airline_theme='simple'

if has("gui_running")
    " unicode symbols
    " let g:airline_left_sep = '»'
    "let g:airline_left_sep = '▶'
    " let g:airline_right_sep = '«'
    "let g:airline_right_sep = '◀'
    " let g:airline_symbols.crypt = '🔒'
    " let g:airline_symbols.linenr = '␊'
    " let g:airline_symbols.linenr = '␤'
    let g:airline_symbols.linenr = '¶'
    let g:airline_symbols.maxlinenr = '☰'
    " let g:airline_symbols.maxlinenr = ''
    let g:airline_symbols.branch = '⎇'
    " let g:airline_symbols.paste = 'ρ'
    let g:airline_symbols.paste = 'Þ'
    " let g:airline_symbols.paste = '∥'
    let g:airline_symbols.spell = 'Ꞩ'
    let g:airline_symbols.notexists = '∄'
    let g:airline_symbols.whitespace = 'Ξ'
else
    "let g:airline_right_sep = ''
    "let g:airline_left_sep = ''
    let g:airline_symbols.linenr = '¶'
    let g:airline_symbols.maxlinenr = '☰'
    " let g:airline_symbols.maxlinenr = ''
    " let g:airline_symbols.branch = '⎇'
    let g:airline_symbols.branch = ''
    "let g:airline_symbols.branch = '⌥'
    " let g:airline_symbols.paste = 'ρ'
    let g:airline_symbols.paste = 'Þ'
    " let g:airline_symbols.paste = '∥'
    let g:airline_symbols.spell = 'Ꞩ'
    let g:airline_symbols.notexists = '∄'
    let g:airline_symbols.whitespace = 'Ξ'
endif

    let g:airline#themes#simple#palette = {}

    let s:bg_none = 'NONE'

    let s:guibg = '#080808'
    let s:guibg2 = '#3e515b'
    let s:termbg = s:bg_none
    let s:termbg2= 0

    let s:N1 = [ s:guibg , '#6182b8' , 232 , 4 ]
    let s:N2 = [ '#263238' , '#9e9e9e', s:termbg2, 247 ]
    let s:N3 = [ '#82aaff' , s:guibg2, 12 , 8]
    let g:airline#themes#simple#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
    let g:airline#themes#simple#palette.normal_modified = {
          \ 'airline_c': [ '#ffb62c' , '#3e515b', 3, 8   , ''     ] ,
          \ }


    let s:I1 = [ s:guibg, '#ffb62c' , 232 , 3 ]
    let s:I2 = s:N2
    let s:I3 = [ '#ffcb6b' , s:guibg2, 11 , 8 ]
    let g:airline#themes#simple#palette.insert = airline#themes#generate_color_map(s:I1, s:I2, s:I3)
    let g:airline#themes#simple#palette.insert_modified = copy(g:airline#themes#simple#palette.normal_modified)
    let g:airline#themes#simple#palette.insert_paste = {
          \ 'airline_a': [ s:I1[0]   , '#d78700' , s:I1[2] , 172     , ''     ] ,
          \ }


    let g:airline#themes#simple#palette.replace = {
          \ 'airline_a': [ s:I1[0]   , '#af0000' , s:I1[2] , 1     , ''     ] ,
          \ }
    let g:airline#themes#simple#palette.replace_modified = copy(g:airline#themes#simple#palette.normal_modified)


    let s:V1 = [ s:guibg, '#91b859' , 232, 10]
    let s:V2 = s:N2
    let s:V3 = [ '#c3e88d' , s:guibg2, 2 , 8 ]
    let g:airline#themes#simple#palette.visual = airline#themes#generate_color_map(s:V1, s:V2, s:V3)
    let g:airline#themes#simple#palette.visual_modified = copy(g:airline#themes#simple#palette.normal_modified)


    let s:IA  = [ '#d75f5f' , s:guibg2  , 167 , 8 , '' ]
    let s:IA2 = [ '#6182b8' , s:guibg2 , 12 , 8, '' ]
    let g:airline#themes#simple#palette.inactive = airline#themes#generate_color_map(s:IA, s:IA2, s:IA2)
    let g:airline#themes#simple#palette.inactive_modified = {
          \ 'airline_c': [ '#ffcb6b', '', 3, '', '' ] ,
          \ }

    " Warnings
    let s:WI = [ '#282C34', '#E5C07B', 16, 202 ]
    let g:airline#themes#simple#palette.normal.airline_warning = [
                \ s:WI[0], s:WI[1], s:WI[2], s:WI[3]
                \ ]

    let g:airline#themes#simple#palette.normal_modified.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.insert.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.insert_modified.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.visual.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.visual_modified.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.replace.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.replace_modified.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    " Errors
    let s:ER = [ '#282C34', '#E06C75', 16, 1 ]
    let g:airline#themes#simple#palette.normal.airline_error = [
                \ s:ER[0], s:ER[1], s:ER[2], s:ER[3]
                \ ]

    let g:airline#themes#simple#palette.normal_modified.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.insert.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.insert_modified.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.visual.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.visual_modified.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.replace.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.replace_modified.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error
" }}}

