set nocompatible
filetype off
execute pathogen#infect()
filetype plugin indent on



" Set 999 lines to the cursor - when moving vertically using j/k
" Keeps cursor centered
set so=999
set sidescroll=1
set sidescrolloff=15

" Turn on the WiLd menu
set wildmenu

set wildmode=longest,list
" Ignore compiled files
set wildignore+=*.o,*~,*.pyc,*.versionsBackup
set wildignore+=*/target/*

" Don't insert comment when using 'o'
au FileType * set fo-=o

"Always show current position
set ruler

" Height of the command bar
set cmdheight=1

" A buffer becomes hidden when it is abandoned
set hidden

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch

" Don't redraw while executing macros (good performance config)
set lazyredraw

" For regular expressions turn magic on
set magic

" Show matching brackets when text indicator is over them
set showmatch
" How many tenths of a second to blink when matching brackets
set mat=2

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Use 256 colors
set t_Co=256

" Make splits behave better
set splitbelow
set splitright

" Make moving around splits easier
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" General options
let python_hightlight_all=1
set background=dark
syntax on
colorscheme hybrid_material
set nu
set relativenumber
set hlsearch
set clipboard=unnamed
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set noshowmode
set ruler
set showmatch
set nowrap
set laststatus=2
set cindent
set cinkeys-=0#
set indentkeys-=0#
let g:is_posix = 1
"set nofoldenable

" make leader a more sane keybinding
let mapleader = "\<Space>"

" remap localleader
let maplocalleader = ","

" Change tabs to be 2 spaces for xml files
autocmd FileType xml setlocal shiftwidth=2 tabstop=2 softtabstop=2
" enable xml folding
let g:xml_syntax_folding=1

autocmd BufNewFile,BufRead *.zsh-theme set syntax=zsh
autocmd BufNewFile,BufRead *.dbs set syntax=xml

" fold based on syntax
set foldmethod=syntax

" Make enter create a new line
nnoremap <CR> o<ESC>

" make 0 work better
nnoremap 0 ^
nnoremap ^ 0

" Better backups
" set nobackup
set backupdir=/tmp
set noswapfile

" Fold toggle keybind
nnoremap <Leader>a za

" Make <Leader>q clear highlighting from searches
nnoremap <silent> <Leader>q :noh<return><esc>

" emacs bindings
" <c-a> don't work with tmux
" inoremap <c-a> <esc>I
inoremap <c-e> <esc>A
" nnoremap <c-a> <home>
nnoremap <c-e> <end>

"autocmd BufWritePost *.py :PymodeLintAuto
set foldlevel=99

" make it easier to use buffers
nnoremap <Leader>l :bn<CR>
nnoremap <Leader>h :bp<CR>
map <Leader><Leader> :b#<CR>
map <Leader>p :bp<CR>

" more standard 'close tab' behavior
nnoremap <C-x> :bd<CR>

" treat wrapped lines as different lines
noremap j gj
noremap k gk
noremap gj j
noremap gk k

" easier to go to end/beginning of lines
noremap L $
noremap H ^

" Buffer keymappings
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>

map <Leader>o :only<CR>


" netrw setup {{{
let g:netrw_winsize = -28
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4


" }}}

" Easier to save
nnoremap <C-s> :w<CR>
nnoremap q :q<CR>
nnoremap Q q
imap <C-s> <Esc>:w<CR>i
nnoremap <Leader>x :q<CR>

" Easier to exit insert mode
inoremap jk <Esc>

" keybinding to see whitespace
nnoremap <Leader>z :set invlist<CR>
set listchars=tab:>-,trail:~,extends:>,space:.

"make folding work better with insert mode
autocmd InsertEnter * if !exists('w:last_fdm') | let w:last_fdm=&foldmethod | setlocal foldmethod=manual | endif
autocmd InsertLeave,WinLeave * if exists('w:last_fdm') | let &l:foldmethod=w:last_fdm | unlet w:last_fdm | endif

" Set up supertab
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabContextTextOmniPrecedence = ['&omnifunc', '&completefunc']

" Ansible setup {{{
let g:ansible_unindent_after_newline = 1
let g:ansible_attribute_highlight = "a"
" let g:ansible_name_highlight = 'd'
let g:ansible_extra_keywords_highlight = 1

" ALE setup {{{
nmap <silent> ]e <Plug>(ale_next_wrap)
nmap <silent> [e <Plug>(ale_previous_wrap)
let g:ale_python_flake8_options = '--max-line-length 99'
let g:ale_virtualenv_dir_names = []
let g:ale_lint_on_text_changed = 'never'
" }}}

" Easymotion setup {{{
map <Leader> <Plug>(easymotion-prefix)
nmap s <Plug>(easymotion-overwin-f)
map / <Plug>(easymotion-sn)
omap / <Plug><easymotion-tn)
let g:EasyMotion_startofline = 0

" }}}

" Airline setup {{{
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
set laststatus=2

let g:airline_section_c = '%t'
let g:airline_section_x = ' '
let g:airline_section_y = '%y'
let g:airline_section_z = '%{&ff} %3l:%2c'
" }}}

" Set up ctrlP
set runtimepath^=~/.vim/bundle/ctrlp.vim

" Set up rainbow parens
let g:rainbow_active = 1

let g:rainbow_conf = {
            \ 'ctermfgs': ['lightcyan','yellow','lightgreen','lightmagenta'],
            \ 'separately': {
            \   'xml': 0
            \  }
            \}


if has("gui_running")
    colorscheme material-theme
    set guifont=Liberation\ Mono\ for\ Powerline\ Regular\ 11
    set guioptions-=T
    set guioptions+=e
    set guioptions-=m
    set guitablabel=%M\ %t
    let g:airline_theme='hybrid'
    " set lines=35 columns=110
else
    " Set line number color as darkgray
    highlight LineNr ctermfg=8
    let g:hybrid_custom_term_colors=1
    set background=dark
    let g:airline_theme='simple'
endif

if has("win32unix")
    let g:airline_symbols_ascii = 1
else
    let g:airline_powerline_fonts = 1
end

" More Airline {{{
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

if has("gui_running")
    " unicode symbols
    " let g:airline_left_sep = '»'
    "let g:airline_left_sep = '▶'
    " let g:airline_right_sep = '«'
    "let g:airline_right_sep = '◀'
    " let g:airline_symbols.crypt = '🔒'
    " let g:airline_symbols.linenr = '␊'
    " let g:airline_symbols.linenr = '␤'
    let g:airline_symbols.linenr = '¶'
    let g:airline_symbols.maxlinenr = '☰'
    " let g:airline_symbols.maxlinenr = ''
    let g:airline_symbols.branch = '⎇'
    " let g:airline_symbols.paste = 'ρ'
    let g:airline_symbols.paste = 'Þ'
    " let g:airline_symbols.paste = '∥'
    let g:airline_symbols.spell = 'Ꞩ'
    let g:airline_symbols.notexists = '∄'
    let g:airline_symbols.whitespace = 'Ξ'
else
    "let g:airline_right_sep = ''
    "let g:airline_left_sep = ''
    let g:airline_symbols.linenr = '¶'
    let g:airline_symbols.maxlinenr = '☰'
    " let g:airline_symbols.maxlinenr = ''
    let g:airline_symbols.branch = '⎇'
    "let g:airline_symbols.branch = '⌥'
    " let g:airline_symbols.paste = 'ρ'
    let g:airline_symbols.paste = 'Þ'
    " let g:airline_symbols.paste = '∥'
    let g:airline_symbols.spell = 'Ꞩ'
    let g:airline_symbols.notexists = '∄'
    let g:airline_symbols.whitespace = 'Ξ'

    let g:airline#themes#simple#palette = {}

    let s:bg_none = 'NONE'

    let s:guibg = '#080808'
    let s:guibg2 = '#1c1c1c'
    let s:termbg = s:bg_none
    let s:termbg2= 0

    let s:N1 = [ s:guibg , '#00dfff' , s:termbg2 , 247 ]
    let s:N2 = [ '#ff5f00' , s:guibg2, 'gray', 8 ]
    let s:N3 = [ '#767676' , s:guibg, 10 , s:termbg2]
    let g:airline#themes#simple#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
    let g:airline#themes#simple#palette.normal_modified = {
          \ 'airline_c': [ '#df0000' , s:guibg, 11, s:termbg   , ''     ] ,
          \ }


    let s:I1 = [ s:guibg, '#5fff00' , s:termbg2 , 11 ]
    let s:I2 = [ '#ff5f00' , s:guibg2, 'gray', 8 ]
    let s:I3 = [ '#767676' , s:guibg, 243 , s:termbg2 ]
    let g:airline#themes#simple#palette.insert = airline#themes#generate_color_map(s:I1, s:I2, s:I3)
    let g:airline#themes#simple#palette.insert_modified = copy(g:airline#themes#simple#palette.normal_modified)
    let g:airline#themes#simple#palette.insert_paste = {
          \ 'airline_a': [ s:I1[0]   , '#d78700' , s:I1[2] , 172     , ''     ] ,
          \ }


    let g:airline#themes#simple#palette.replace = {
          \ 'airline_a': [ s:I1[0]   , '#af0000' , s:I1[2] , 124     , ''     ] ,
          \ }
    let g:airline#themes#simple#palette.replace_modified = copy(g:airline#themes#simple#palette.normal_modified)


    let s:V1 = [ s:guibg, '#dfdf00' , 'black', 2]
    let s:V2 = [ '#ff5f00' , s:guibg2, 'gray', 8 ]
    let s:V3 = [ '#767676' , s:guibg, 243 , s:termbg2 ]
    let g:airline#themes#simple#palette.visual = airline#themes#generate_color_map(s:V1, s:V2, s:V3)
    let g:airline#themes#simple#palette.visual_modified = copy(g:airline#themes#simple#palette.normal_modified)


    let s:IA  = [ '#4e4e4e' , s:guibg  , 239 , s:termbg2 , '' ]
    let s:IA2 = [ '#4e4e4e' , s:guibg2 , 239 , s:termbg2, '' ]
    let g:airline#themes#simple#palette.inactive = airline#themes#generate_color_map(s:IA, s:IA2, s:IA2)
    let g:airline#themes#simple#palette.inactive_modified = {
          \ 'airline_c': [ '#df0000', '', 160, '', '' ] ,
          \ }

    " Warnings
    let s:WI = [ '#282C34', '#E5C07B', 16, 202 ]
    let g:airline#themes#simple#palette.normal.airline_warning = [
                \ s:WI[0], s:WI[1], s:WI[2], s:WI[3]
                \ ]

    let g:airline#themes#simple#palette.normal_modified.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.insert.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.insert_modified.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.visual.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.visual_modified.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.replace.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    let g:airline#themes#simple#palette.replace_modified.airline_warning =
                \ g:airline#themes#simple#palette.normal.airline_warning

    " Errors
    let s:ER = [ '#282C34', '#E06C75', 16, 1 ]
    let g:airline#themes#simple#palette.normal.airline_error = [
                \ s:ER[0], s:ER[1], s:ER[2], s:ER[3]
                \ ]

    let g:airline#themes#simple#palette.normal_modified.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.insert.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.insert_modified.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.visual.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.visual_modified.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.replace.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error

    let g:airline#themes#simple#palette.replace_modified.airline_error =
                \ g:airline#themes#simple#palette.normal.airline_error
    let g:airline_skip_empty_sections = 1
endif
" }}}

