#!/usr/bin/env bash
# short-story-md - Fetch a Shortcut story and format it as markdown
# Usage: short-story-md <story-id>
set -o errexit -o nounset -o pipefail

short story "${1}" --format "%j" | jq -r '"## " + .name + "\n\n" + (.description // "")'
