#! /usr/bin/env sh
sudo apt install libncurses5-dev python2.7 python2.7-dev python3 python3-dev libperl-dev ruby-dev lua5.3 liblua5.3-dev ruby ruby-dev
sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.3.so /usr/local/lib/liblua.so
sudo apt install libx11-dev libxtst-dev libxt-dev libsm-dev libxpm-dev libgtk-3-dev

