#!/bin/sh
set -o errexit -o nounset

TAG="${1:-core}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

"$SCRIPT_DIR/install-tools" "$TAG"
"$SCRIPT_DIR/install-symlinks"
"$SCRIPT_DIR/install-pack"
vim +helptags\ ALL +qall
