#!/usr/bin/env sh

# java \
# 	-Declipse.application=org.eclipse.jdt.ls.core.id1 \
# 	-Dosgi.bundles.defaultStartLevel=4 \
# 	-Declipse.product=org.eclipse.jdt.ls.core.product \
# 	-Dlog.level=ALL \
# 	-noverify \
# 	-Xms1G \
#     -jar ~/jdt-language-server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar \
# 	-configuration ~/jdt-language-server/config_linux \
# 	-data ~/projects/entweb

java \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -Dlog.level=ALL \
    -noverify \
    -Xmx1G \
    -jar ~/jdt-language-server/plugins/org.eclipse.equinox.launcher_1.6.400.v20210908-1257.jar \
    -configuration ~/jdt-language-server/config_linux \
    -data ~/projects/entweb \
    --add-modules=ALL-SYSTEM \
    --add-opens java.base/java.util=ALL-UNNAMED \
    --add-opens java.base/java.lang=ALL-UNNAMED


# java \
# 	-Declipse.application=org.eclipse.jdt.ls.core.id1 \
# 	-Dosgi.bundles.defaultStartLevel=4 \
# 	-Declipse.product=org.eclipse.jdt.ls.core.product \
# 	-Dlog.level=ALL \
# 	-noverify \
# 	-Xms1G \
# 	-jar ~/jdt-language-server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar \
# 	-configuration ~/jdt-language-server/config_linux \
# 	-data ~/projects/weblogic
    # -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044 \
    # -Xbootclasspath/a:/home/warden/.m2/repository/org/projectlombok/lombok/1.18.12/lombok-1.18.12.jar \
# java \
#     -Declipse.application=org.eclipse.jdt.ls.core.id1 \
#     -Dosgi.bundles.defaultStartLevel=4 \
#     -Declipse.product=org.eclipse.jdt.ls.core.product \
#     -Dlog.level=ALL \
#     -noverify \
#     -Xmx1G \
#     -javaagent:/home/warden/.m2/repository/org/projectlombok/lombok/1.18.12/lombok-1.18.12.jar \
#     -jar /home/warden/jdt-language-server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar \
#     -configuration /home/warden/jdt-language-server/config_linux \
#     -data /home/warden/projects/weblogic \
#     --add-modules=ALL-SYSTEM \
#     --add-opens java.base/java.util=ALL-UNNAMED \
#     --add-opens java.base/java.lang=ALL-UNNAMED
