#!/bin/sh

cmd=$(basename "$1")
shift

case $cmd in
    install)
        exec "$HOME/.bin/jzd-install" "$@" ;;
    256)
        exec "$HOME/.bin/jzd-256-colors" "$@" ;;
    color) # 256colors
        exec "$HOME/.bin/jzd-colortrans" "$@" ;;
    theme)
        exec "$HOME/.bin/jzd-theme" "$@" ;;
    *)
        echo "$(basename "$0") $cmd: unknown command" ;;
esac
