#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/git-ctags.XXXXXX")
trap 'rm -rf "$tmpdir"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$tmpdir/tags"
sed -e 's#^\([^	][^	]*\)\(	..*\)\(\1\)\(.*\)$#\1\2\\zs\3\4#g' "$tmpdir/tags" > "$tmpdir/tags.out"
mv "$tmpdir/tags.out" "tags"
