#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$$.tags"
mv "$$.tags" "tags"
sed -i '' 's#^\([^	][^	]*\)\(	..*\)\(\1\)\(.*\)$#\1\2\\zs\3\4#g' "tags"
